#! /bin/sh
set -euf

realpath() {
  python -c 'import os, sys; print os.path.realpath(sys.argv[1])' "$1"
}

tools="$(dirname "$(realpath "$0")")"; export tools
script="$("$tools/read-config.json")"
eval "$script"
exec "$tools/$method/$action"
