#! /bin/sh
set -xeuf

plugins="$(json-print $file package $target plists PhoneGap Plugins | plugins2args)"
echo "$plugins" | while read name value; do
  if test -d app/plugins/$name; then

    h_files="$(cd app/plugins/$name && find . -name '*.h')"
    cpp_files="$(cd app/plugins/$name && find . -name '*.cpp')"
    mm_files="$(cd app/plugins/$name && find . -name '*.mm')"
    js_files="$(cd app/plugins/$name && find . -name '*.js')"

    {
      echo "$h_files"
      echo "$cpp_files"
      echo "$mm_files"
    } |
        tar -C app/plugins/$name -T- -c |
        tar -C "$(find iOS-project -type d -name Plugins)" -x -v

    {
      echo "$js_files"
    } |
        tar -C app/plugins/$name -T- -c |
        tar -C iOS-project/www -x -v

    # link js to html
    gsedi iOS-project/www/index.html "s:</head>:$(
      echo "$js_files" | sed '
          s:^\./\(.*\):<script type="application/javascript" src="\1"></script>:
      ')\n&:"
  fi
done
