#! /bin/sh
set -xeuf

plugins="$(json-print $file package $target plists PhoneGap Plugins | plugins2args)"
echo "$plugins" | while read name value; do
  if test -d app/plugins/$name; then

    h_files="$(cd app/plugins/$name && find . -name '*.h')"
    cpp_files="$(cd app/plugins/$name && find . -name '*.cpp')"
    mm_files="$(cd app/plugins/$name && find . -name '*.mm')"
    js_files="$(cd app/plugins/$name && find . -name '*.js')"

    plugins_dir="$(find iOS-project -type d -name Plugins)"
    test $(echo "$plugins_dir" | wc -l) = 1

    {
      echo "$h_files"
      echo "$cpp_files"
      echo "$mm_files"
    } |
        tar -C app/plugins/$name -T- -c |
        tar -C "$plugins_dir" -x -v

    # link plugins source files to pbxproj
    pbxproj_plist="iOS-project/$activity.xcodeproj/project.pbxproj"
    pbxproj_json="$pbxproj_plist.json"
    plutil -convert json "$pbxproj_plist" -o "$pbxproj_json"
    {
      echo "$cpp_files"
      echo "$mm_files"
    } |
        while read file; do
          pbx-add-plugin-source-file "$pbxproj_json" "$plugins_dir/$file"
        done
    pbx-json2plist < "$pbxproj_json" > "$pbxproj_plist"
    cat "$pbxproj_json" # debug output
    cat "$pbxproj_plist" # debug output
    rm "$pbxproj_json"

    {
      echo "$js_files"
    } |
        tar -C app/plugins/$name -T- -c |
        tar -C iOS-project/www -x -v

    # link js to html
    gsedi iOS-project/www/index.html "s:</head>:$(
      echo "$js_files" | sed '
          s:^\./\(.*\):<script type="application/javascript" src="\1"></script>:
      ')\n&:"
  fi
done
