#! /bin/sh
# create iOS project directory
set -xeuf

package="${1-$package}"
activity="${2-$activity}"

cd $ROOT/../submodules/github/4z3/callback-ios/
./bin/create "$OLDPWD/iOS-project" "$package" "$activity"
cd "$OLDPWD"
rm -fR iOS-project/www
mkdir iOS-project/www
