#! /bin/sh
set -xeu

# configuration
export build_dir="${build_dir-$PWD}"
# !4 iOS: phonegap_dir="${phonegap_dir-$HOME/phonegap-1.1.0}"
export sdk="${sdk}"
export activity="${activity-MyActivity}"
export package="${package-com.test.mypackage}"

# sanity-check configuration
validate-activity
validate-package
validate-build_dir
validate-sdk iphonesimulator

# setup self-destructive working directory
cd "`mktemp -d "${TMPDIR-/tmp}/package-phonegap-iOS.XXXXXXXXXX"`"
trap "cd '$OLDPWD'; rm -fR '$PWD'" EXIT INT QUIT
# !4 iOS: ln -s "$phonegap_dir/iOS" phonegap
ln -s "$build_dir" src

setup-project

# build iOS package
cd iOS-project
gsedi phonegap/debug 's/^xcodebuild/exec &/'
sh phonegap/debug "$PWD" "$activity"

# prepare launcher
(cd $ROOT/../submodules/github/Fingertips/ios-sim
  rake install prefix="$ROOT/phonegap-ios/ios-sim")
sim="$ROOT/phonegap-ios/ios-sim/bin/ios-sim"
chmod 0755 "$sim"

printf '\n\e[1;33mAbort debug output and return to shell with \e[35m^C\e[33m.\e[m\n\n'

# run package
("$sim" launch "build/Release-iphonesimulator/$activity.app")
