#! /bin/sh
set -xeuf

/usr/libexec/PlistBuddy -x -c "Delete :CFBundleIconFiles" \
    iOS-project/$activity/$activity-info.plist
/usr/libexec/PlistBuddy -x -c "Add :CFBundleIconFiles array" \
    iOS-project/$activity/$activity-info.plist
while read px name; do
  if test -e src/theme/images/icon-$px.png; then
    cp src/theme/images/icon-$px.png \
        iOS-project/$activity/Resources/icons/$name
    /usr/libexec/PlistBuddy -x -c "Add :CFBundleIconFiles: string $name" \
        iOS-project/$activity/$activity-info.plist
  fi
done<<EOF
 57 icon.png
114 icon@2x.png
 72 icon-72.png
 29 icon-Small.png
 50 icon-Small-50.png
 58 icon-Small@2x.png
EOF
