#! /bin/sh
set -xeuf

if json-print $file package $target plists PhoneGap | json2plist > myPhoneGap.plist 2>/dev/null; then
  /usr/libexec/PlistBuddy -x \
      -c "Merge iOS-project/$activity/PhoneGap.plist" \
      myPhoneGap.plist
  mv myPhoneGap.plist iOS-project/$activity/PhoneGap.plist
else
  rm myPhoneGap.plist
fi

if json-print $file package $target plists info | json2plist > myInfo.plist 2>/dev/null; then
  /usr/libexec/PlistBuddy -x \
      -c "Merge iOS-project/$activity/$activity-info.plist" \
      myInfo.plist
  mv myInfo.plist iOS-project/$activity/$activity-info.plist
else
  rm myInfo.plist
fi
