#! /bin/sh
set -xeuf

/usr/libexec/PlistBuddy -x -c "Delete :CFBundleIconFiles" \
    iOS-project/$activity/$activity-info.plist
/usr/libexec/PlistBuddy -x -c "Add :CFBundleIconFiles array" \
    iOS-project/$activity/$activity-info.plist
while read px name; do
  if test -e src/theme/images/appicon-$px.png; then
    cp src/theme/images/appicon-$px.png \
        iOS-project/$activity/Resources/icons/$name
  elif test "${autoScaleIcon-false}" = true; then
    if test -e src/theme/images/appicon.png; then
      convert src/theme/images/appicon.png \
          -resize ${px}x$px \
          iOS-project/$activity/Resources/icons/$name
    else
      echo "Warning: missing appicon.png to autoScaleIcon" >&2
      continue
    fi
  else
    echo "Warning: missing appicon-$px.png and autoScaleIcon is not true" >&2
    continue
  fi
  /usr/libexec/PlistBuddy -x -c "Add :CFBundleIconFiles: string $name" \
      iOS-project/$activity/$activity-info.plist
done<<EOF
 57 appicon.png
114 appicon@2x.png
 72 appicon-72.png
 29 appicon-Small.png
 50 appicon-Small-50.png
 58 appicon-Small@2x.png
EOF
