#! /bin/sh
set -xeuf

if test -e src/theme/images/splash.png; then
  cp src/theme/images/splash.png \
      iOS-project/$activity/Resources/splash/Default.png
fi
while read orientation; do
  if test -e src/theme/images/splash-$orientation.png; then
    cp src/theme/images/splash-$orientation.png \
        iOS-project/$activity/Resources/splash/Default-$orientation.png
  fi
done<<EOF
Portrait
PortraitUpsideDown
Landscape
LandscapeLeft
LandscapeRight
EOF
