#! /bin/sh
set -xeu

# configuration
build_dir="${build_dir-$PWD}"
phonegap_dir="${phonegap_dir-$HOME/phonegap-1.1.0}"
target="${target}"
mode="${mode-release}"
activity="${activity-MyActivity}"
package="${package-com.test.mypackage}"

# TODO validate $target
# TODO validate $mode
# TODO validate $activity
# TODO validate $package
# TODO validate $build_dir [i.e. $build_dir/index.html]

# setup self-destructive working directory
cd "`mktemp -d`"
trap "cd '$OLDPWD'; rm -fR '$PWD'" EXIT INT QUIT
ln -s "$phonegap_dir/Android" phonegap
ln -s "$build_dir" src

# create android project directory
android create project \
    --path android-project \
    --activity "$activity" \
    --package "$package" \
    --target "$target"
mkdir android-project/assets

# copy application files into android project directory
cp -R src/* android-project/assets/
# remove potential cruft
rm -f android-project/assets/config.json
rm -f android-project/assets/*.apk

# copy phonegap files into the android project directory
cp phonegap/phonegap-*.js android-project/assets/phonegap.js
cp phonegap/phonegap-*.jar android-project/libs/phonegap.jar
cp -R phonegap/xml android-project/res/

# update android project files to use phonegap
gsedi android-project/src/`echo $package | tr . /`/$activity.java '
  s|extends Activity|extends DroidGap|
  s|setContentView([^)]*)|super.loadUrl("file:///android_asset/index.html")|
  s|import android.app.Activity|import com.phonegap.*|
'
gsedi android-project/AndroidManifest.xml '
  s|.*versionName.*|&\
    <supports-screens\
            android:largeScreens="true"\
            android:normalScreens="true"\
            android:smallScreens="true"\
            android:resizeable="true"\
            android:anyDensity="true"\
            />\
    <uses-permission android:name="android.permission.CAMERA" />\
    <uses-permission android:name="android.permission.VIBRATE" />\
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />\
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />\
    <uses-permission android:name="android.permission.ACCESS_LOCATION_EXTRA_COMMANDS" />\
    <uses-permission android:name="android.permission.READ_PHONE_STATE" />\
    <uses-permission android:name="android.permission.INTERNET" />\
    <uses-permission android:name="android.permission.RECEIVE_SMS" />\
    <uses-permission android:name="android.permission.RECORD_AUDIO" />\
    <uses-permission android:name="android.permission.MODIFY_AUDIO_SETTINGS" />\
    <uses-permission android:name="android.permission.READ_CONTACTS" />\
    <uses-permission android:name="android.permission.WRITE_CONTACTS" />\
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />\
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />|
'
gsedi android-project/assets/index.html '
  s|\(.*<![Dd][Oo][Cc][Tt][Yy][Pp][Ee]  *[Hh][Tt][Mm][Ll]>\)\(.*\)|\1<script type="text/javascript" charset="utf-8" src="phonegap.js"></script>\2|
'

# build android package
(cd android-project && ant --noconfig "$mode")

# emit android package
cp android-project/bin/*.apk src/
