#! /bin/sh
set -xeu

path="$(mktemp -u -d "$PWD/build/$method.XXXXXXXXXX")"
trap "rm -fR '$path'" EXIT INT QUIT

android create project \
    --activity "$activity" \
    --package "$package" \
    --path "$path" \
    --target "$target"

cd "$path"

P=phonegap-1.1.0
T=Android

S="$HOME/$P/$T"

mkdir -p libs/
mkdir -p assets/www/

cp "$S/$P.js" assets/www/
cp "$S/$P.jar" libs/
cp -r "$S/xml" res/

src="`find src -name '*.java'`"
mv "$src" "$src.orig"
sed '
  s;extends Activity;extends DroidGap;
  s;setContentView([^)]*);super.loadUrl("file:///android_asset/www/index.html");
  s;import android.app.Activity;import com.phonegap.*;
' "$src.orig" > "$src"
rm "$src.orig"

##
src=AndroidManifest.xml
mv "$src" "$src.orig"
sed '
  s.*versionName.*&\
    <supports-screens\
            android:largeScreens="true"\
            android:normalScreens="true"\
            android:smallScreens="true"\
            android:resizeable="true"\
            android:anyDensity="true"\
            />\
    <uses-permission android:name="android.permission.CAMERA" />\
    <uses-permission android:name="android.permission.VIBRATE" />\
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />\
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />\
    <uses-permission android:name="android.permission.ACCESS_LOCATION_EXTRA_COMMANDS" />\
    <uses-permission android:name="android.permission.READ_PHONE_STATE" />\
    <uses-permission android:name="android.permission.INTERNET" />\
    <uses-permission android:name="android.permission.RECEIVE_SMS" />\
    <uses-permission android:name="android.permission.RECORD_AUDIO" />\
    <uses-permission android:name="android.permission.MODIFY_AUDIO_SETTINGS" />\
    <uses-permission android:name="android.permission.READ_CONTACTS" />\
    <uses-permission android:name="android.permission.WRITE_CONTACTS" />\
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />\
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
' "$src.orig" > "$src"
rm "$src.orig"

cd -

cp -r "$srcdir"/* "$path/assets/www/"

src="$path/assets/www/index.html"
mv "$src" "$src.orig"
sed '
  s|\(.*<![Dd][Oo][Cc][Tt][Yy][Pp][Ee]  *[Hh][Tt][Mm][Ll]>\)\(.*\)|\1<script type="text/javascript" charset="utf-8" src="'"$P.js"'"></script>\2|
' "$src.orig" > "$src"
rm "$src.orig"

cd -
ant "${mode-release}"

mv bin/*.apk ..
