#! /bin/sh
set -euf

realpath() {
  python -c 'import os, sys; print(os.path.realpath(sys.argv[1]))' "$1"
}

ROOT="$(dirname "$(realpath "$0")")"; export ROOT
PATH="$ROOT/bin:${PATH+:$PATH}"; export PATH

script="`read-config`"

eval "$script"

# rewrite method for backward-compatibility
case "$method" in
  (PhoneGap) method=Cordova;;
esac
export method

PATH="$ROOT/$method/$os/bin:${PATH+:$PATH}"; export PATH

cat >&2<<EOF
#
# Espresso package $action $method/$os (`date +'%Y-%d-%m %H:%M:%S %z'`)
#
EOF
exec "$action"
