#! /bin/sh
set -xeuf

plugins="$(json-print $file package $target plugins | plugins2args)"
echo "$plugins" | while read name value; do

  # copy plugin files
  for i in src libs assets; do
    if test -d app/plugins/$name/$i; then
      tar -C app/plugins/$name -c $i | tar -C android-project -x -v
    fi
  done

  # link js to html
  gsedi android-project/assets/index.html "s:</head>:$(
    find app/plugins/$name/assets -name '*.js' | sed '
        s:^app/plugins/'"$name"'/assets/\(.*\):<script type="application/javascript" src="\1"></script>:
    ')\n&:"

  # add element to res/xml/plugins.xml
  echo "    <plugin name=\""$name"\" value=\""$value"\" />" \
      >> android-project/res/xml/plugins.xml
done

code='<!-- ZXing activities -->
    <activity android:name="com.google.zxing.client.android.CaptureActivity"
              android:screenOrientation="landscape"
              android:configChanges="orientation|keyboardHidden"
              android:theme="@android:style/Theme.NoTitleBar.Fullscreen"
              android:windowSoftInputMode="stateAlwaysHidden">
      <intent-filter>
        <action android:name="com.phonegap.plugins.barcodescanner.SCAN"/>
        <category android:name="android.intent.category.DEFAULT"/>
      </intent-filter>
    </activity>
    <activity android:name="com.google.zxing.client.android.encode.EncodeActivity" android:label="@string/share_name">
      <intent-filter>
        <action android:name="com.phonegap.plugins.barcodescanner.ENCODE"/>
        <category android:name="android.intent.category.DEFAULT"/>
      </intent-filter>
    </activity>'
gsedi android-project/AndroidManifest.xml "s</application>$(
  echo -n "$code" | sed 's/$/\\/'
)\n&"

# move closing tag to the end
gsedi android-project/res/xml/plugins.xml 's:</plugins>::'
echo '</plugins>' \
    >>android-project/res/xml/plugins.xml
