#! /bin/sh
set -xeuf

## remove closing tag from res/xml/plugins.xml
tmp=$(mktemp plugins.xml.XXXXXXXX)
sed -n '/^<\/plugins>$/!p' \
    android-project/res/xml/plugins.xml > $tmp
mv $tmp android-project/res/xml/plugins.xml

## process plugins
json-print $file package $target plugins | plugins2args |
while read name value; do

  # copy plugin files
  for i in src libs assets; do
    if test -d app/plugins/$name/$i; then
      tar -C app/plugins/$name -c $i | tar -C android-project -x -v
    fi
  done

  # link js to html
  tmp=$(mktemp $name,index.html,XXXXXXXX)
  sed "s:</head>:$(
    find app/plugins/$name/assets -name '*.js' | sed -r '
        s:^app/plugins/'"$name"'/assets/(.*):<script type="application/javascript" src="\1"></script>:
    ')\n&:" \
      android-project/assets/index.html > $tmp
  mv $tmp android-project/assets/index.html

  # add element to res/xml/plugins.xml
  echo "    <plugin name=\""$name"\" value=\""$value"\" />" \
      >> android-project/res/xml/plugins.xml
done

## add closing tag again
echo '</plugins>' \
    >>android-project/res/xml/plugins.xml
