#! /bin/sh
set -eu

sdks="`android list target | sed -n 's/^id:.*"\(.*\)"$/\1/p'`"

if ! echo "$sdks" | grep -q "^$sdk$"; then
  exec >&2
  echo 'The sdk specified in config.json is not available on this system!'
  if test -z "$sdks"; then
    echo 'Please install the Android SDK.'
  else
    echo "Possible sdk-choices for \"package $action\" are:"
    echo "$sdks" | sed 's/^/    /'
  fi
  exit 23
fi

